"""Cached Discord guild snapshot for the control panel (channels, roles, sync queue).

The 24/7 bot writes this data via ``sync_guild_full_snapshot``; the panel API on
Render reads it so dropdowns work without an attached discord.py process.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from orbat_db import _get_pool, _utc_now_iso


def init_guild_cache_db() -> None:
    statements = [
        """
        CREATE TABLE IF NOT EXISTS guild_channels (
            guild_id BIGINT NOT NULL,
            channel_id BIGINT NOT NULL,
            name TEXT NOT NULL,
            channel_type TEXT NOT NULL,
            category_id BIGINT,
            category_name TEXT NOT NULL DEFAULT '',
            sort_position INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (guild_id, channel_id)
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_guild_channels_type ON guild_channels(guild_id, channel_type)",
        """
        CREATE TABLE IF NOT EXISTS guild_roles (
            guild_id BIGINT NOT NULL,
            role_id BIGINT NOT NULL,
            name TEXT NOT NULL,
            color INTEGER NOT NULL DEFAULT 0,
            sort_position INTEGER NOT NULL DEFAULT 0,
            managed SMALLINT NOT NULL DEFAULT 0,
            PRIMARY KEY (guild_id, role_id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS guild_sync_state (
            guild_id BIGINT PRIMARY KEY,
            last_sync_at TEXT,
            last_sync_by TEXT NOT NULL DEFAULT '',
            sync_requested_at TEXT,
            member_count INTEGER NOT NULL DEFAULT 0,
            channel_count INTEGER NOT NULL DEFAULT 0,
            role_count INTEGER NOT NULL DEFAULT 0,
            guild_name TEXT NOT NULL DEFAULT ''
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS member_actions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            guild_id BIGINT NOT NULL,
            discord_id BIGINT NOT NULL,
            action_type TEXT NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            processed_at TEXT
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_member_actions_pending ON member_actions(guild_id, processed_at)",
    ]
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            for statement in statements:
                cur.execute(statement)
        conn.commit()


def replace_guild_channels(guild_id: int, channels: list[dict[str, Any]]) -> None:
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM guild_channels WHERE guild_id = %s", (guild_id,))
            if channels:
                cur.executemany(
                    """
                    INSERT INTO guild_channels (
                        guild_id, channel_id, name, channel_type,
                        category_id, category_name, sort_position
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                    """,
                    [
                        (
                            guild_id,
                            ch["channel_id"],
                            ch["name"],
                            ch["channel_type"],
                            ch.get("category_id"),
                            ch.get("category_name") or "",
                            ch.get("sort_position", 0),
                        )
                        for ch in channels
                    ],
                )
        conn.commit()


def replace_guild_roles(guild_id: int, roles: list[dict[str, Any]]) -> None:
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM guild_roles WHERE guild_id = %s", (guild_id,))
            if roles:
                cur.executemany(
                    """
                    INSERT INTO guild_roles (
                        guild_id, role_id, name, color, sort_position, managed
                    ) VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    [
                        (
                            guild_id,
                            r["role_id"],
                            r["name"],
                            r.get("color", 0),
                            r.get("sort_position", 0),
                            1 if r.get("managed") else 0,
                        )
                        for r in roles
                    ],
                )
        conn.commit()


def set_sync_complete(
    guild_id: int,
    *,
    guild_name: str,
    member_count: int,
    channel_count: int,
    role_count: int,
    synced_by: str = "bot",
) -> None:
    now = _utc_now_iso()
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO guild_sync_state (
                    guild_id, last_sync_at, last_sync_by, sync_requested_at,
                    member_count, channel_count, role_count, guild_name
                ) VALUES (%s, %s, %s, NULL, %s, %s, %s, %s)
                ON CONFLICT (guild_id) DO UPDATE SET
                    last_sync_at = EXCLUDED.last_sync_at,
                    last_sync_by = EXCLUDED.last_sync_by,
                    sync_requested_at = NULL,
                    member_count = EXCLUDED.member_count,
                    channel_count = EXCLUDED.channel_count,
                    role_count = EXCLUDED.role_count,
                    guild_name = EXCLUDED.guild_name
                """,
                (guild_id, now, synced_by, member_count, channel_count, role_count, guild_name),
            )
        conn.commit()


def request_sync(guild_id: int) -> None:
    now = _utc_now_iso()
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO guild_sync_state (guild_id, sync_requested_at)
                VALUES (%s, %s)
                ON CONFLICT (guild_id) DO UPDATE SET sync_requested_at = EXCLUDED.sync_requested_at
                """,
                (guild_id, now),
            )
        conn.commit()


def get_sync_state(guild_id: int) -> dict[str, Any]:
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT * FROM guild_sync_state WHERE guild_id = %s", (guild_id,))
            row = cur.fetchone()
            if row is None:
                return {
                    "guild_id": guild_id,
                    "last_sync_at": None,
                    "last_sync_by": "",
                    "sync_requested_at": None,
                    "member_count": 0,
                    "channel_count": 0,
                    "role_count": 0,
                    "guild_name": "",
                }
            return dict(row)


def guilds_pending_sync() -> list[int]:
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT guild_id FROM guild_sync_state
                WHERE sync_requested_at IS NOT NULL
                ORDER BY sync_requested_at
                """
            )
            return [int(row["guild_id"]) for row in cur.fetchall()]


def get_guild_directory(guild_id: int) -> dict[str, Any]:
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT channel_id, name, channel_type, category_name
                FROM guild_channels
                WHERE guild_id = %s
                ORDER BY sort_position, lower(name)
                """,
                (guild_id,),
            )
            channels = [dict(row) for row in cur.fetchall()]

            cur.execute(
                """
                SELECT role_id, name, color
                FROM guild_roles
                WHERE guild_id = %s
                ORDER BY sort_position DESC, lower(name)
                """,
                (guild_id,),
            )
            roles = [dict(row) for row in cur.fetchall()]

            cur.execute(
                """
                SELECT discord_id, username, nickname
                FROM members
                WHERE guild_id = %s AND active = 1
                ORDER BY lower(COALESCE(NULLIF(nickname, ''), username))
                LIMIT 500
                """,
                (guild_id,),
            )
            members = [dict(row) for row in cur.fetchall()]

    text_channels = []
    voice_channels = []
    categories = []
    for ch in channels:
        entry = {
            "id": str(ch["channel_id"]),
            "name": ch["name"],
            "category": ch["category_name"] or None,
        }
        if ch["channel_type"] == "text":
            text_channels.append(entry)
        elif ch["channel_type"] == "voice":
            voice_channels.append(entry)
        elif ch["channel_type"] == "category":
            categories.append(entry)

    sync = get_sync_state(guild_id)
    return {
        "text_channels": text_channels,
        "voice_channels": voice_channels,
        "categories": categories,
        "roles": [
            {"id": str(r["role_id"]), "name": r["name"], "color": r["color"]}
            for r in roles
        ],
        "members": [
            {
                "id": str(m["discord_id"]),
                "name": m["nickname"] or m["username"],
            }
            for m in members
        ],
        "sync": sync,
        "from_cache": True,
    }


def enqueue_member_action(
    guild_id: int,
    discord_id: int,
    action_type: str,
    payload: dict[str, Any],
) -> int:
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO member_actions (guild_id, discord_id, action_type, payload, created_at)
                VALUES (%s, %s, %s, %s::jsonb, %s)
                RETURNING id
                """,
                (guild_id, discord_id, action_type, json.dumps(payload), _utc_now_iso()),
            )
            action_id = int(cur.fetchone()["id"])
        conn.commit()
        return action_id


def fetch_pending_member_actions(guild_id: int, limit: int = 20) -> list[dict[str, Any]]:
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, guild_id, discord_id, action_type, payload, created_at
                FROM member_actions
                WHERE guild_id = %s AND processed_at IS NULL
                ORDER BY id
                LIMIT %s
                """,
                (guild_id, limit),
            )
            rows = []
            for row in cur.fetchall():
                item = dict(row)
                if isinstance(item.get("payload"), str):
                    item["payload"] = json.loads(item["payload"])
                rows.append(item)
            return rows


def mark_member_action_processed(action_id: int) -> None:
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE member_actions SET processed_at = %s WHERE id = %s",
                (_utc_now_iso(), action_id),
            )
        conn.commit()
